name: Build CLI

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: builds
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - run: zip -r linux ds-api-client
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: linux.zip
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - run: zip -r macos ds-api-client
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: macos.zip
