name: Build CLI

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build for Linux
        run: bun run compile:linux
      - name: Build for macOS
        run: bun run compile:darwin
      - name: Build for windows
        run: bun run compile:windows
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "ds-api-client-linux-x64, ds-api-client-darwin-arm64, ds-api-client.exe"
          artifactErrorsFailBuild: true
