name: Build CLI

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    permissions:
      contents: write
    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v3
        with:
          name: linux.zip
      - name: Download macOS build
        uses: actions/download-artifact@v3
        with:
          name: macos.zip
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generateReleaseNotes: true
          artifacts: linux.zip, macos.zip
          artifactErrorsFailBuild: true
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - run: zip -r linux ds-api-client
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: linux.zip
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - run: zip -r macos ds-api-client
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          path: macos.zip
