name: Build CLI

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    permissions:
      contents: write
    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ds-api-client-linux
          path: linux/
      - name: Download macOS build
        uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ds-api-client-macos
          path: macos/
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generateReleaseNotes: true
          artifacts: "linux/ds-api-client, macos/ds-api-client"
          artifactErrorsFailBuild: true
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ds-api-client-linux
          path: ds-api-client
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run compile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ds-api-client-macos
          path: ds-api-client
